name: Testing Turbo Build & Lint

on:
  - push
  - pull_request

permissions: read-all

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Launch Turbo Remote Cache Server
        uses: dtinth/setup-github-actions-caching-for-turbo@v1.1.0

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm i

      - name: Setup Prisma
        run: cd packages/web && pnpm prisma generate && cd ../../

      - name: Lint
        run: pnpm run lint

      - name: Build
        run: NEXT_PUBLIC_SUPABASE_URL="https://this-is-dummy-url" NEXT_PUBLIC_SUPABASE_ANON_KEY="dummy key" pnpm run build
