name: Testing Turbo Build & Lint

on:
  - push
  - pull_request

permissions: read-all

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Launch Turbo Remote Cache Server
        uses: dtinth/setup-github-actions-caching-for-turbo@v1.1.0

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - name: Build
        run: pnpm run build
        env:
          SUPABASE_APP_URL: http://localhost:3000
          API_ENDPOINT: http://localhost:8000/api
          VITE_API_ENDPOINT: http://localhost:8000/api
          SUPABASE_URL: http://127.0.0.1:54321
          NEXT_PUBLIC_SUPABASE_URL: http://127.0.0.1:54321
          SUPABASE_ANON_KEY: REPLACE_ME_WITH_YOUR_ANON_KEY
          NEXT_PUBLIC_SUPABASE_ANON_KEY: REPLACE_ME_WITH_YOUR_ANON_KEY
          DATABASE_URL: postgresql://postgres:postgres@127.0.0.1:54322/postgres

      - name: Lint
        run: pnpm run lint
        env:
          SUPABASE_APP_URL: http://localhost:3000
          API_ENDPOINT: http://localhost:8000/api
          VITE_API_ENDPOINT: http://localhost:8000/api
          SUPABASE_URL: http://127.0.0.1:54321
          NEXT_PUBLIC_SUPABASE_URL: http://127.0.0.1:54321
          SUPABASE_ANON_KEY: REPLACE_ME_WITH_YOUR_ANON_KEY
          NEXT_PUBLIC_SUPABASE_ANON_KEY: REPLACE_ME_WITH_YOUR_ANON_KEY
          DATABASE_URL: postgresql://postgres:postgres@127.0.0.1:54322/postgres
